name: Lab 4 CI Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
<<<<<<< HEAD
 lint:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Use Node.js 18.x
    uses: actions/setup-node@v3
    with:
      node-version: "18"
  - name: Install dependencies
    run: npm clean-install
  - name: Run linter
    run: npm run lint
=======
	lint:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v3
		- name: Use Node.js 18.x
		  uses: actions/setup-node@v3
		  with:
			node-version: "18"
		- name: Install dependencies
		  run: npm clean-install
		- name: Run linter
		  run: npm run lint
>>>>>>> 2a0a1a5ed25b8963f2757496a50fd7224f84a9e4
